// Domain preset registry — the front/back contract for per-channel routing chips.
// Only `{id, label, category}` lives here; the curated domain lists themselves are
// a server concern (packages/server/src/modules/channels/presets.ts) since the web
// only needs enough to render grouped chips, never the underlying domains.
// One preset = one resource (a single service, or — for `torrent` — the one
// established "pack of trackers" case). `category` groups presets in the UI only;
// it never affects domain resolution, which stays flat over every preset id.

// Fixed set of group captions — every preset's `category` below is checked against
// this via `satisfies`, so a typo (a new category not in this list, or a stray
// variant of an existing one) is a compile error instead of a silent phantom group
// in PresetChips.
const PRESET_CATEGORIES = [
  "Видео",
  "Мессенджеры",
  "AI",
  "Разработка",
  "Продуктивность",
  "Соцсети",
  "Стриминг",
  "Гейминг",
  "Финансы",
  "P2P",
] as const;
type PresetCategory = (typeof PRESET_CATEGORIES)[number];

export const CHANNEL_PRESETS = [
  { id: "youtube", label: "YouTube", category: "Видео" },
  { id: "lampa", label: "Lampa", category: "Видео" },
  { id: "tmdb", label: "TMDB", category: "Видео" },
  { id: "dailymotion", label: "Dailymotion", category: "Видео" },
  { id: "rumble", label: "Rumble", category: "Видео" },
  { id: "bilibili", label: "Bilibili", category: "Видео" },
  { id: "odysee", label: "Odysee", category: "Видео" },
  { id: "nebula", label: "Nebula", category: "Видео" },
  { id: "ted", label: "TED", category: "Видео" },
  { id: "niconico", label: "Niconico", category: "Видео" },
  { id: "telegram", label: "Telegram", category: "Мессенджеры" },
  { id: "whatsapp", label: "WhatsApp", category: "Мессенджеры" },
  { id: "signal", label: "Signal", category: "Мессенджеры" },
  { id: "viber", label: "Viber", category: "Мессенджеры" },
  { id: "discord", label: "Discord", category: "Мессенджеры" },
  { id: "slack", label: "Slack", category: "Мессенджеры" },
  { id: "line", label: "LINE", category: "Мессенджеры" },
  { id: "wechat", label: "WeChat", category: "Мессенджеры" },
  { id: "element", label: "Element", category: "Мессенджеры" },
  { id: "threema", label: "Threema", category: "Мессенджеры" },
  { id: "openai", label: "OpenAI", category: "AI" },
  { id: "claude", label: "Claude", category: "AI" },
  { id: "gemini", label: "Gemini", category: "AI" },
  { id: "perplexity", label: "Perplexity", category: "AI" },
  { id: "grok", label: "Grok", category: "AI" },
  { id: "copilot", label: "Copilot", category: "AI" },
  { id: "cursor", label: "Cursor", category: "AI" },
  { id: "deepseek", label: "DeepSeek", category: "AI" },
  { id: "mistral", label: "Mistral", category: "AI" },
  { id: "huggingface", label: "Hugging Face", category: "AI" },
  { id: "suno", label: "Suno", category: "AI" },
  { id: "elevenlabs", label: "ElevenLabs", category: "AI" },
  { id: "runway", label: "Runway", category: "AI" },
  { id: "ideogram", label: "Ideogram", category: "AI" },
  { id: "characterai", label: "Character.AI", category: "AI" },
  { id: "poe", label: "Poe", category: "AI" },
  { id: "leonardo", label: "Leonardo", category: "AI" },
  { id: "midjourney", label: "Midjourney", category: "AI" },
  { id: "github", label: "GitHub", category: "Разработка" },
  { id: "gitlab", label: "GitLab", category: "Разработка" },
  { id: "npm", label: "npm", category: "Разработка" },
  { id: "pypi", label: "PyPI", category: "Разработка" },
  { id: "dockerhub", label: "Docker Hub", category: "Разработка" },
  { id: "stackoverflow", label: "Stack Overflow", category: "Разработка" },
  { id: "jetbrains", label: "JetBrains", category: "Разработка" },
  { id: "vercel", label: "Vercel", category: "Разработка" },
  { id: "netlify", label: "Netlify", category: "Разработка" },
  { id: "replit", label: "Replit", category: "Разработка" },
  { id: "microsoft365", label: "Microsoft 365", category: "Продуктивность" },
  { id: "googledrive", label: "Google Drive", category: "Продуктивность" },
  { id: "notion", label: "Notion", category: "Продуктивность" },
  { id: "figma", label: "Figma", category: "Продуктивность" },
  { id: "dropbox", label: "Dropbox", category: "Продуктивность" },
  { id: "zoom", label: "Zoom", category: "Продуктивность" },
  { id: "atlassian", label: "Atlassian", category: "Продуктивность" },
  { id: "instagram", label: "Instagram", category: "Соцсети" },
  { id: "x", label: "X", category: "Соцсети" },
  { id: "facebook", label: "Facebook", category: "Соцсети" },
  { id: "tiktok", label: "TikTok", category: "Соцсети" },
  { id: "reddit", label: "Reddit", category: "Соцсети" },
  { id: "linkedin", label: "LinkedIn", category: "Соцсети" },
  { id: "pinterest", label: "Pinterest", category: "Соцсети" },
  { id: "snapchat", label: "Snapchat", category: "Соцсети" },
  { id: "bluesky", label: "Bluesky", category: "Соцсети" },
  { id: "threads", label: "Threads", category: "Соцсети" },
  { id: "tumblr", label: "Tumblr", category: "Соцсети" },
  { id: "netflix", label: "Netflix", category: "Стриминг" },
  { id: "disneyplus", label: "Disney+", category: "Стриминг" },
  { id: "spotify", label: "Spotify", category: "Стриминг" },
  { id: "twitch", label: "Twitch", category: "Стриминг" },
  { id: "soundcloud", label: "SoundCloud", category: "Стриминг" },
  { id: "applemusic", label: "Apple Music", category: "Стриминг" },
  { id: "hbomax", label: "Max", category: "Стриминг" },
  { id: "primevideo", label: "Prime Video", category: "Стриминг" },
  { id: "crunchyroll", label: "Crunchyroll", category: "Стриминг" },
  { id: "vimeo", label: "Vimeo", category: "Стриминг" },
  { id: "deezer", label: "Deezer", category: "Стриминг" },
  { id: "tidal", label: "Tidal", category: "Стриминг" },
  { id: "steam", label: "Steam", category: "Гейминг" },
  { id: "epicgames", label: "Epic Games", category: "Гейминг" },
  { id: "playstation", label: "PlayStation", category: "Гейминг" },
  { id: "xbox", label: "Xbox", category: "Гейминг" },
  { id: "battlenet", label: "Battle.net", category: "Гейминг" },
  { id: "riotgames", label: "Riot Games", category: "Гейминг" },
  { id: "nintendo", label: "Nintendo", category: "Гейминг" },
  { id: "ea", label: "EA", category: "Гейминг" },
  { id: "ubisoft", label: "Ubisoft", category: "Гейминг" },
  { id: "gog", label: "GOG", category: "Гейминг" },
  { id: "roblox", label: "Roblox", category: "Гейминг" },
  { id: "rockstar", label: "Rockstar", category: "Гейминг" },
  { id: "binance", label: "Binance", category: "Финансы" },
  { id: "coinbase", label: "Coinbase", category: "Финансы" },
  { id: "bybit", label: "Bybit", category: "Финансы" },
  { id: "kraken", label: "Kraken", category: "Финансы" },
  { id: "tradingview", label: "TradingView", category: "Финансы" },
  { id: "paypal", label: "PayPal", category: "Финансы" },
  { id: "wise", label: "Wise", category: "Финансы" },
  { id: "torrent", label: "Torrent", category: "P2P" },
  { id: "soulseek", label: "Soulseek", category: "P2P" },
] as const satisfies readonly { id: string; label: string; category: PresetCategory }[];

export type PresetId = (typeof CHANNEL_PRESETS)[number]["id"];
