// Domain preset registry — the front/back contract for per-channel routing chips.
// `{id, label, category}` drives the chip UI; `PRESET_DOMAINS` (below) holds the
// curated domain list behind each preset. Both live here (not server-only) because
// the web now needs the domains too — chip tooltips list them on hover, and the
// server's resolveMatcherDomains expands the same map into DOMAIN-SUFFIX rules.
// One preset = one resource (a single service, or — for `torrent` — the one
// established "pack of trackers" case). `category` groups presets in the UI only;
// it never affects domain resolution, which stays flat over every preset id.

// Fixed set of group captions — every preset's `category` below is checked against
// this via `satisfies`, so a typo (a new category not in this list, or a stray
// variant of an existing one) is a compile error instead of a silent phantom group
// in PresetChips.
const PRESET_CATEGORIES = [
  "Видео",
  "Мессенджеры",
  "AI",
  "Разработка",
  "Продуктивность",
  "Соцсети",
  "Стриминг",
  "Гейминг",
  "Финансы",
  "P2P",
] as const;
type PresetCategory = (typeof PRESET_CATEGORIES)[number];

export const CHANNEL_PRESETS = [
  { id: "youtube", label: "YouTube", category: "Видео" },
  { id: "lampa", label: "Lampa", category: "Видео" },
  { id: "tmdb", label: "TMDB", category: "Видео" },
  { id: "dailymotion", label: "Dailymotion", category: "Видео" },
  { id: "rumble", label: "Rumble", category: "Видео" },
  { id: "bilibili", label: "Bilibili", category: "Видео" },
  { id: "odysee", label: "Odysee", category: "Видео" },
  { id: "nebula", label: "Nebula", category: "Видео" },
  { id: "ted", label: "TED", category: "Видео" },
  { id: "niconico", label: "Niconico", category: "Видео" },
  { id: "telegram", label: "Telegram", category: "Мессенджеры" },
  { id: "whatsapp", label: "WhatsApp", category: "Мессенджеры" },
  { id: "signal", label: "Signal", category: "Мессенджеры" },
  { id: "viber", label: "Viber", category: "Мессенджеры" },
  { id: "discord", label: "Discord", category: "Мессенджеры" },
  { id: "slack", label: "Slack", category: "Мессенджеры" },
  { id: "line", label: "LINE", category: "Мессенджеры" },
  { id: "wechat", label: "WeChat", category: "Мессенджеры" },
  { id: "element", label: "Element", category: "Мессенджеры" },
  { id: "threema", label: "Threema", category: "Мессенджеры" },
  { id: "openai", label: "OpenAI", category: "AI" },
  { id: "claude", label: "Claude", category: "AI" },
  { id: "gemini", label: "Gemini", category: "AI" },
  { id: "perplexity", label: "Perplexity", category: "AI" },
  { id: "grok", label: "Grok", category: "AI" },
  { id: "copilot", label: "Copilot", category: "AI" },
  { id: "cursor", label: "Cursor", category: "AI" },
  { id: "deepseek", label: "DeepSeek", category: "AI" },
  { id: "mistral", label: "Mistral", category: "AI" },
  { id: "huggingface", label: "Hugging Face", category: "AI" },
  { id: "suno", label: "Suno", category: "AI" },
  { id: "elevenlabs", label: "ElevenLabs", category: "AI" },
  { id: "runway", label: "Runway", category: "AI" },
  { id: "ideogram", label: "Ideogram", category: "AI" },
  { id: "characterai", label: "Character.AI", category: "AI" },
  { id: "poe", label: "Poe", category: "AI" },
  { id: "leonardo", label: "Leonardo", category: "AI" },
  { id: "midjourney", label: "Midjourney", category: "AI" },
  { id: "github", label: "GitHub", category: "Разработка" },
  { id: "gitlab", label: "GitLab", category: "Разработка" },
  { id: "bitbucket", label: "Bitbucket", category: "Разработка" },
  { id: "npm", label: "npm", category: "Разработка" },
  { id: "pypi", label: "PyPI", category: "Разработка" },
  { id: "dockerhub", label: "Docker Hub", category: "Разработка" },
  { id: "stackoverflow", label: "Stack Overflow", category: "Разработка" },
  { id: "vscode", label: "VS Code", category: "Разработка" },
  { id: "jetbrains", label: "JetBrains", category: "Разработка" },
  { id: "postman", label: "Postman", category: "Разработка" },
  { id: "sentry", label: "Sentry", category: "Разработка" },
  { id: "cloudflare", label: "Cloudflare", category: "Разработка" },
  { id: "vercel", label: "Vercel", category: "Разработка" },
  { id: "netlify", label: "Netlify", category: "Разработка" },
  { id: "replit", label: "Replit", category: "Разработка" },
  { id: "codesandbox", label: "CodeSandbox", category: "Разработка" },
  { id: "stackblitz", label: "StackBlitz", category: "Разработка" },
  { id: "sourcegraph", label: "Sourcegraph", category: "Разработка" },
  { id: "pencil", label: "Pencil", category: "Разработка" },
  { id: "microsoft365", label: "Microsoft 365", category: "Продуктивность" },
  { id: "googledrive", label: "Google Drive", category: "Продуктивность" },
  { id: "notion", label: "Notion", category: "Продуктивность" },
  { id: "figma", label: "Figma", category: "Продуктивность" },
  { id: "dropbox", label: "Dropbox", category: "Продуктивность" },
  { id: "zoom", label: "Zoom", category: "Продуктивность" },
  { id: "atlassian", label: "Atlassian", category: "Продуктивность" },
  { id: "instagram", label: "Instagram", category: "Соцсети" },
  { id: "x", label: "X", category: "Соцсети" },
  { id: "facebook", label: "Facebook", category: "Соцсети" },
  { id: "tiktok", label: "TikTok", category: "Соцсети" },
  { id: "reddit", label: "Reddit", category: "Соцсети" },
  { id: "linkedin", label: "LinkedIn", category: "Соцсети" },
  { id: "pinterest", label: "Pinterest", category: "Соцсети" },
  { id: "snapchat", label: "Snapchat", category: "Соцсети" },
  { id: "bluesky", label: "Bluesky", category: "Соцсети" },
  { id: "threads", label: "Threads", category: "Соцсети" },
  { id: "tumblr", label: "Tumblr", category: "Соцсети" },
  { id: "netflix", label: "Netflix", category: "Стриминг" },
  { id: "disneyplus", label: "Disney+", category: "Стриминг" },
  { id: "spotify", label: "Spotify", category: "Стриминг" },
  { id: "twitch", label: "Twitch", category: "Стриминг" },
  { id: "soundcloud", label: "SoundCloud", category: "Стриминг" },
  { id: "applemusic", label: "Apple Music", category: "Стриминг" },
  { id: "hbomax", label: "HBO Max", category: "Стриминг" },
  { id: "primevideo", label: "Prime Video", category: "Стриминг" },
  { id: "crunchyroll", label: "Crunchyroll", category: "Стриминг" },
  { id: "vimeo", label: "Vimeo", category: "Стриминг" },
  { id: "deezer", label: "Deezer", category: "Стриминг" },
  { id: "tidal", label: "Tidal", category: "Стриминг" },
  { id: "steam", label: "Steam", category: "Гейминг" },
  { id: "epicgames", label: "Epic Games", category: "Гейминг" },
  { id: "playstation", label: "PlayStation", category: "Гейминг" },
  { id: "xbox", label: "Xbox", category: "Гейминг" },
  { id: "battlenet", label: "Battle.net", category: "Гейминг" },
  { id: "riotgames", label: "Riot Games", category: "Гейминг" },
  { id: "nintendo", label: "Nintendo", category: "Гейминг" },
  { id: "ea", label: "EA", category: "Гейминг" },
  { id: "ubisoft", label: "Ubisoft", category: "Гейминг" },
  { id: "gog", label: "GOG", category: "Гейминг" },
  { id: "roblox", label: "Roblox", category: "Гейминг" },
  { id: "rockstar", label: "Rockstar", category: "Гейминг" },
  { id: "binance", label: "Binance", category: "Финансы" },
  { id: "coinbase", label: "Coinbase", category: "Финансы" },
  { id: "bybit", label: "Bybit", category: "Финансы" },
  { id: "kraken", label: "Kraken", category: "Финансы" },
  { id: "tradingview", label: "TradingView", category: "Финансы" },
  { id: "paypal", label: "PayPal", category: "Финансы" },
  { id: "wise", label: "Wise", category: "Финансы" },
  { id: "torrent", label: "Torrent", category: "P2P" },
  { id: "soulseek", label: "Soulseek", category: "P2P" },
] as const satisfies readonly { id: string; label: string; category: PresetCategory }[];

export type PresetId = (typeof CHANNEL_PRESETS)[number]["id"];

// Curated domain list behind each preset id. Entries are bare apex/second-level
// hosts — the server expands them into `DOMAIN-SUFFIX` rules (which also match all
// subdomains), and the web lists them in each chip's hover tooltip. The
// `Record<PresetId, string[]>` type makes a missing/extra id a compile error.
export const PRESET_DOMAINS: Record<PresetId, string[]> = {
  youtube: [
    "youtube.com",
    "googlevideo.com",
    "ytimg.com",
    "youtu.be",
    "youtubei.googleapis.com",
    "ggpht.com",
    "youtube-nocookie.com",
  ],
  lampa: ["lampa.mx", "lampa.app", "lampa.run", "lampa.stream", "cub.red", "cub.rip"],
  tmdb: ["themoviedb.org", "tmdb.org"],
  dailymotion: ["dailymotion.com", "dai.ly", "dmcdn.net"],
  rumble: ["rumble.com", "rmbl.ws"],
  bilibili: ["bilibili.com", "bilibili.tv", "hdslb.com", "bilivideo.com"],
  odysee: ["odysee.com", "odycdn.com"],
  nebula: ["nebula.tv"],
  ted: ["ted.com"],
  niconico: ["nicovideo.jp", "nimg.jp"],
  telegram: ["telegram.org", "t.me", "telegram.me", "tdesktop.com", "telesco.pe", "telegra.ph"],
  discord: [
    "discord.com",
    "discord.gg",
    "discordapp.com",
    "discordapp.net",
    "discord.media",
    "discordcdn.com",
  ],
  torrent: [
    "rutracker.org",
    "nnmclub.to",
    "rutor.info",
    "1337x.to",
    "thepiratebay.org",
    "torrentgalaxy.to",
    "nyaa.si",
    "yts.mx",
    "eztv.re",
  ],
  soulseek: ["slsknet.org"],
  whatsapp: ["whatsapp.com", "whatsapp.net"],
  signal: ["signal.org"],
  viber: ["viber.com"],
  openai: [
    "openai.com",
    "chatgpt.com",
    "oaistatic.com",
    "oaiusercontent.com",
    "sora.com",
    "openai.fm",
  ],
  claude: [
    "anthropic.com",
    "claude.ai",
    "claudeusercontent.com",
    "anthropic.gallerycdn.vsassets.io",
  ],
  gemini: [
    "gemini.google.com",
    "bard.google.com",
    "aistudio.google.com",
    "makersuite.google.com",
    "generativelanguage.googleapis.com",
  ],
  perplexity: ["perplexity.ai"],
  grok: ["x.ai", "grok.com"],
  copilot: ["githubcopilot.com", "copilot.microsoft.com"],
  cursor: ["cursor.com", "cursor.sh", "cursorapi.com", "cursor-cdn.com"],
  deepseek: ["deepseek.com"],
  mistral: ["mistral.ai"],
  huggingface: ["huggingface.co", "hf.co"],
  suno: ["suno.com", "suno.ai"],
  elevenlabs: ["elevenlabs.io"],
  runway: ["runwayml.com"],
  ideogram: ["ideogram.ai"],
  characterai: ["character.ai"],
  poe: ["poe.com"],
  leonardo: ["leonardo.ai"],
  midjourney: ["midjourney.com"],
  github: ["github.com", "githubusercontent.com", "githubassets.com", "github.io", "ghcr.io"],
  gitlab: ["gitlab.com", "gitlab.io"],
  bitbucket: ["bitbucket.org", "bitbucket.io"],
  npm: ["npmjs.com", "npmjs.org"],
  pypi: ["pypi.org", "pythonhosted.org"],
  dockerhub: ["docker.com", "docker.io"],
  stackoverflow: ["stackoverflow.com", "stackexchange.com", "sstatic.net"],
  vscode: ["code.visualstudio.com", "marketplace.visualstudio.com", "vscode.dev"],
  jetbrains: ["jetbrains.com"],
  postman: ["postman.com", "getpostman.com"],
  sentry: ["sentry.io"],
  cloudflare: ["cloudflare.com", "cloudflareworkers.com", "workers.dev", "pages.dev"],
  vercel: ["vercel.com", "vercel.app"],
  netlify: ["netlify.com", "netlify.app"],
  replit: ["replit.com", "repl.co"],
  codesandbox: ["codesandbox.io", "codesandbox.dev"],
  stackblitz: ["stackblitz.com", "webcontainer.io"],
  sourcegraph: ["sourcegraph.com"],
  pencil: ["pencil.dev", "pen.dev"],
  microsoft365: [
    "office.com",
    "office365.com",
    "microsoft365.com",
    "sharepoint.com",
    "onedrive.com",
    "outlook.com",
  ],
  googledrive: ["drive.google.com", "docs.google.com", "sheets.google.com", "slides.google.com"],
  notion: ["notion.so", "notion.com", "notion.site"],
  figma: ["figma.com"],
  dropbox: ["dropbox.com", "dropboxusercontent.com"],
  zoom: ["zoom.us", "zoom.com"],
  atlassian: ["atlassian.com", "atlassian.net"],
  slack: ["slack.com", "slack-edge.com"],
  line: ["line.me", "line-scdn.net"],
  wechat: ["wechat.com", "weixin.qq.com", "wx.qq.com"],
  element: ["element.io", "matrix.org"],
  threema: ["threema.ch"],
  instagram: ["instagram.com", "cdninstagram.com"],
  x: ["x.com", "twitter.com", "twimg.com"],
  facebook: ["facebook.com", "fbcdn.net"],
  tiktok: ["tiktok.com", "tiktokcdn.com", "ttwstatic.com"],
  reddit: ["reddit.com", "redditstatic.com", "redd.it"],
  linkedin: ["linkedin.com", "licdn.com"],
  pinterest: ["pinterest.com", "pinimg.com"],
  snapchat: ["snapchat.com", "sc-cdn.net"],
  bluesky: ["bsky.app", "bsky.social"],
  threads: ["threads.net"],
  tumblr: ["tumblr.com"],
  netflix: ["netflix.com", "nflxvideo.net", "nflximg.net", "nflxext.com"],
  disneyplus: ["disneyplus.com", "disney-plus.net", "dssott.com"],
  spotify: ["spotify.com", "scdn.co"],
  twitch: ["twitch.tv", "ttvnw.net", "jtvnw.net"],
  soundcloud: ["soundcloud.com", "sndcdn.com"],
  applemusic: ["music.apple.com"],
  hbomax: ["max.com", "hbomax.com"],
  primevideo: ["primevideo.com"],
  crunchyroll: ["crunchyroll.com"],
  vimeo: ["vimeo.com", "vimeocdn.com"],
  deezer: ["deezer.com", "dzcdn.net"],
  tidal: ["tidal.com"],
  steam: ["steampowered.com", "steamcommunity.com", "steamstatic.com", "steamcontent.com"],
  epicgames: ["epicgames.com", "unrealengine.com"],
  playstation: ["playstation.com", "playstation.net", "sonyentertainmentnetwork.com"],
  xbox: ["xbox.com", "xboxlive.com"],
  battlenet: ["battle.net", "blizzard.com"],
  riotgames: ["riotgames.com", "leagueoflegends.com", "playvalorant.com", "riotcdn.net"],
  nintendo: ["nintendo.com", "nintendo.net", "nintendoswitch.com"],
  ea: ["ea.com", "origin.com"],
  ubisoft: ["ubisoft.com", "ubi.com"],
  gog: ["gog.com"],
  roblox: ["roblox.com", "rbxcdn.com"],
  rockstar: ["rockstargames.com"],
  binance: ["binance.com"],
  coinbase: ["coinbase.com"],
  bybit: ["bybit.com"],
  kraken: ["kraken.com"],
  tradingview: ["tradingview.com"],
  paypal: ["paypal.com", "paypalobjects.com"],
  wise: ["wise.com"],
};
